#!/usr/bin/env sh

# Generate changelog
npx auto-changelog

# Stage the changelog
git add CHANGELOG.md

# Check if there are changes to commit
if git diff --staged --quiet; then
  echo "✨ No changes to CHANGELOG.md"
else
  # Commit the changelog changes
  git commit -m "update: update changelog [skip ci]"
fi
